const skillData = [
  {
    skillName: "Frontend",
    progress: 90,
    color: "blue",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Recoil",
      "MobX",
      "Zustand",
      "React-query",
      "Tailwind CSS",
      "Chakra UI",
      "Material UI",
      "VISX",
    ],
  },
  {
    skillName: "Android",
    progress: 60,
    color: "green",
    tags: [
      "Java",
      "Kotlin",
      "Android SDK",
      "Android Jetpack",
      "Koin",
      "Dexter",
      "Data Binding",
      "Retrofit",
      "LiveData",
      "Room",
      "Realm",
    ],
  },
  {
    skillName: "Backend",
    progress: 50,
    color: "red",
    tags: [
      "Node.js",
      "Express",
      "TypeScript",
      "Golang",
      "Gin",
      "MongoDB",
      "GraphQL",
      "Apollo",
      "Prisma",
      "Docker",
      "GCP",
    ],
  },
  {
    skillName: "Others",
    progress: 40,
    color: "yellow",
    tags: [
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "Confluence",
      "Slack",
      "Notion",
      "Figma",
      "Docker",
      "GCP",
      "Firebase",
      "Selenium",
      "Tensorite",
    ],
  },
];

const steps = [
  {
    title: "Phill-IT",
    startDate: "2017. 01",
    endDate: "2018. 09",
    role: "Researcher, Android Developer",
    description: [
      "안드로이드 환경의 필기 인식 모듈 개발",
      "사용자 입력 키워드 기반 연계 광고 모듈 개발",
      "사용자 입력 키워드 기반 단어 추천 모듈 개발 참여",
    ],
  },
  {
    title: "Cyberlogitec",
    startDate: "2018. 10",
    endDate: "Working",
    role: "Android Developer, Frontend Developer",
    description: [
      "해운 물류 산업 기반 포워딩 플랫폼의 안드로이드/프론트엔드 개발",
      "블록체인 기반 컨테이너 검사 신청 시스템의 안드로이드 개발",
      "컨테이너 유지 보수 이력 관리 시스템의 안드로이드 개발",
      "선사 업무 지원 솔루션의 UI/UX 개선 사업의 퍼블리싱 수행",
      "포워딩 관련 신사업 프로젝트의 프론트엔드 개발 담당",
      "사내 터미널 운영 관리 솔루션의 프론트엔드 개발 담당",
      "컨테이너 자원 관리 솔루션 Refactoring 프로젝트의 프론트엔드 개발 담당",
    ],
  },
  {
    title: "Next..?",
    startDate: "",
    endDate: "",
    role: "Wait for the next challenge!",
    description: [],
  },
];

export { steps, skillData };
