import { ProjectInfoType, ProjectType } from "@/lib/typeDef";

const ProjectList: ProjectInfoType[] = [
  {
    pid: "freight9",
    type: [ProjectType.Frontend, ProjectType.Android],
    title: "Freight9",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr: "해운 물류 포워딩 플랫폼 프로젝트",
    startDate: new Date("2018-10-01"),
    endDate: new Date("2021-04-01"),
  },
  {
    pid: "allegro",
    type: [ProjectType.Frontend],
    title: "Allegro",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr: "컨테이너 자원 관리 및 화물 수익성 최적화 솔루션 프로젝트",
    startDate: new Date("2023-03-01"),
    endDate: new Date(),
  },
  {
    pid: "logichain-imdg",
    type: [ProjectType.Android],
    title: "Logichain-IMDG",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr: "블록체인 기반 컨테이너 위험물 검사 신청 시스템 프로젝트",
    startDate: new Date("2020-09-01"),
    endDate: new Date("2020-12-01"),
  },
  {
    pid: "container-mnr",
    type: [ProjectType.Android],
    title: "Container M&R Project",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr:
      "문자 이미지 인식을 활용한 컨테이너 유지보수 관리 시스템 프로젝트",
    startDate: new Date("2021-05-01"),
    endDate: new Date("2022-02-01"),
  },
  {
    pid: "allegro-esvc",
    type: [ProjectType.Frontend],
    title: "Allegro E-Service",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr: "선사 업무 지원용 솔루션 프로젝트",
    startDate: new Date("2022-03-01"),
    endDate: new Date("2022-09-01"),
  },
  {
    pid: "one-modernization",
    type: [ProjectType.Frontend],
    title: "Ocean Network Express Modernization",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr:
      "ONE 그룹 전용 Shipping Monitoring/Forwarding 솔루션 재설계 프로젝트",
    startDate: new Date("2022-09-01"),
    endDate: new Date("2023-05-01"),
  },
  {
    pid: "opus-terminal",
    type: [ProjectType.Frontend],
    title: "OPUS Terminal",
    organization: "Cyberlogitec",
    description_kr: "",
    description_en: "",
    summary_kr:
      "선박 터미널의 선적, 하역, 분류 및 보관 관리용 통합 솔루션 프로젝트",
    startDate: new Date("2023-01-01"),
    endDate: new Date("2023-03-01"),
  },

  {
    pid: "rabit-keyboard",
    type: [ProjectType.General],
    title: "RABIT A-KEYBOARD",
    organization: "Phill-IT",
    description_en: "",
    description_kr: "",
    summary_kr:
      "다국어 언어 지원 및 자동 추천/교정 기능을 지원하는 안드로이드용 가상 키보드 솔루션",
    startDate: new Date("2017-02-01"),
    endDate: new Date("2018-09-01"),
  },
  {
    pid: "dont-panic",
    type: [ProjectType.Frontend],
    title: "Don't Panic",
    organization: "Hyundai Cradle",
    description_kr: "",
    description_en: "",
    summary_kr:
      "비대면 온라인 교육 환경 개선을 위한 메타버스 코딩 플랫폼 프로젝트",
    startDate: new Date("2021-10-01"),
    endDate: new Date("2021-11-01"),
  },
  {
    pid: "applemint",
    type: [ProjectType.Frontend, ProjectType.Backend],
    title: "Applemint",
    organization: "Personal Project",
    description_kr: "",
    description_en: "",
    summary_kr: "웹 사이트 크롤링을 활용한 게시물 피드 서비스",
  },
  {
    pid: "craftman-bartender",
    type: [ProjectType.Android],
    title: "Craftman Bartender",
    organization: "Personal Project",
    description_kr: "",
    description_en: "",
    summary_kr: "조주기능사 실기시험 모의테스트 연습용 안드로이드 앱",
  },
  {
    pid: "meerkat",
    type: [ProjectType.Frontend, ProjectType.Backend],
    title: "Meerkat",
    organization: "Personal Project",
    description_kr: "",
    description_en: "",
    summary_kr:
      "RSS 피드를 통해 수집한 뉴스 키워드와 연관된 주식과 영향도를 보여주는 서비스",
  },
  {
    pid: "barbambar",
    type: [ProjectType.Frontend],
    title: "Barbambar",
    organization: "Personal Project",
    description_kr: "",
    description_en: "",
    summary_kr: "바밤바 프로모션 페이지",
  },
];

export { ProjectList };
